-- Active: 1760541509356@@localhost@5433@visa_application_db
BEGIN;

CREATE SCHEMA IF NOT EXISTS form;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS form.visa_application;

CREATE TABLE form.visa_application (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

    full_name_passport text NOT NULL,
    other_names text NOT NULL DEFAULT '',
    residential_address text NOT NULL,
    residential_address_postal_code text NOT NULL DEFAULT '',
    years_at_address text NOT NULL DEFAULT '',
    months_at_address text NOT NULL DEFAULT '',
    previous_address text NOT NULL DEFAULT '',
    previous_address_from text NOT NULL DEFAULT '',
    previous_address_to text NOT NULL DEFAULT '',
    mobile_phone text NOT NULL,
    email text NOT NULL,
    housing_status text NOT NULL DEFAULT '',
    housing_status_details text NOT NULL DEFAULT '',
    marital_status text NOT NULL DEFAULT '',
    citizenship text NOT NULL DEFAULT '',
    second_citizenship_country text NOT NULL DEFAULT '',
    other_citizenship_country text NOT NULL DEFAULT '',
    birth_date text NOT NULL DEFAULT '',
    birth_country text NOT NULL DEFAULT '',
    birth_place text NOT NULL DEFAULT '',

    current_passport_number text NOT NULL DEFAULT '',
    current_passport_issuing_authority text NOT NULL DEFAULT '',
    current_passport_valid_from text NOT NULL DEFAULT '',
    current_passport_valid_to text NOT NULL DEFAULT '',
    has_other_passport text NOT NULL DEFAULT '',
    other_passport_number text NOT NULL DEFAULT '',
    other_passport_issuing_authority text NOT NULL DEFAULT '',
    other_passport_issue_date text NOT NULL DEFAULT '',
    other_passport_expiry_date text NOT NULL DEFAULT '',
    national_passport_number text NOT NULL DEFAULT '',

    employment_statuses text NOT NULL DEFAULT '',
    organization_name text NOT NULL DEFAULT '',
    organization_address text NOT NULL DEFAULT '',
    work_phone text NOT NULL DEFAULT '',
    work_start_date text NOT NULL DEFAULT '',
    position text NOT NULL DEFAULT '',
    monthly_income_after_tax text NOT NULL DEFAULT '',
    work_description text NOT NULL DEFAULT '',
    has_other_income text NOT NULL DEFAULT '',
    other_income_sources text NOT NULL DEFAULT '',
    other_income_total_year text NOT NULL DEFAULT '',
    has_savings text NOT NULL DEFAULT '',
    savings_balance text NOT NULL DEFAULT '',
    monthly_expenses text NOT NULL DEFAULT '',
    trip_personal_cost text NOT NULL DEFAULT '',
    has_trip_sponsor text NOT NULL DEFAULT '',
    sponsor_type text NOT NULL DEFAULT '',
    sponsor_person_full_name text NOT NULL DEFAULT '',
    sponsor_person_address text NOT NULL DEFAULT '',
    sponsor_person_amount text NOT NULL DEFAULT '',
    sponsor_person_reason text NOT NULL DEFAULT '',
    sponsor_employer_amount text NOT NULL DEFAULT '',
    sponsor_employer_reason text NOT NULL DEFAULT '',
    sponsor_organization_name text NOT NULL DEFAULT '',
    sponsor_organization_address text NOT NULL DEFAULT '',
    sponsor_organization_amount text NOT NULL DEFAULT '',
    sponsor_organization_reason text NOT NULL DEFAULT '',

    arrival_date_uk text NOT NULL DEFAULT '',
    departure_date_uk text NOT NULL DEFAULT '',
    primary_purpose text NOT NULL DEFAULT '',
    travel_with_non_dependent text NOT NULL DEFAULT '',
    companion_full_name text NOT NULL DEFAULT '',
    companion_citizenship text NOT NULL DEFAULT '',
    companion_relationship text NOT NULL DEFAULT '',
    accommodation_type text NOT NULL DEFAULT '',
    hotel_name_and_address text NOT NULL DEFAULT '',
    relative_name_and_address text NOT NULL DEFAULT '',
    friend_name_and_address text NOT NULL DEFAULT '',
    is_business_trip text NOT NULL DEFAULT '',
    business_inviting_company_name text NOT NULL DEFAULT '',
    business_inviter_full_name text NOT NULL DEFAULT '',
    business_inviting_company_activity text NOT NULL DEFAULT '',
    business_inviting_company_address_uk text NOT NULL DEFAULT '',
    business_inviting_company_phone text NOT NULL DEFAULT '',
    business_planned_activities text NOT NULL DEFAULT '',

    spouse_full_name text NOT NULL DEFAULT '',
    spouse_citizenship text NOT NULL DEFAULT '',
    spouse_birth_date text NOT NULL DEFAULT '',
    spouse_passport_number text NOT NULL DEFAULT '',
    spouse_travels_with_applicant text NOT NULL DEFAULT '',
    spouse_lives_with_applicant text NOT NULL DEFAULT '',
    spouse_residential_address text NOT NULL DEFAULT '',
    spouse_residential_country text NOT NULL DEFAULT '',

    father_first_name text NOT NULL DEFAULT '',
    father_last_name text NOT NULL DEFAULT '',
    father_birth_date text NOT NULL DEFAULT '',
    father_citizenship text NOT NULL DEFAULT '',
    father_had_single_citizenship text NOT NULL DEFAULT '',
    father_citizenship_at_applicant_birth text NOT NULL DEFAULT '',

    mother_first_name text NOT NULL DEFAULT '',
    mother_last_name text NOT NULL DEFAULT '',
    mother_birth_date text NOT NULL DEFAULT '',
    mother_citizenship text NOT NULL DEFAULT '',
    mother_had_single_citizenship text NOT NULL DEFAULT '',
    mother_citizenship_at_applicant_birth text NOT NULL DEFAULT '',

    child_has_dependants text NOT NULL DEFAULT '',
    child_full_name text NOT NULL DEFAULT '',
    child_birth_date text NOT NULL DEFAULT '',
    child_birth_place text NOT NULL DEFAULT '',
    child_citizenship text NOT NULL DEFAULT '',
    child_passport_number text NOT NULL DEFAULT '',
    child_travels_with_applicant text NOT NULL DEFAULT '',
    child_lives_with_applicant text NOT NULL DEFAULT '',
    child_residential_address text NOT NULL DEFAULT '',

    has_uk_relatives text NOT NULL DEFAULT '',
    uk_relatives_relationship text NOT NULL DEFAULT '',
    uk_relative_1_full_name text NOT NULL DEFAULT '',
    uk_relative_1_citizenship text NOT NULL DEFAULT '',
    uk_relative_1_stay_basis text NOT NULL DEFAULT '',
    uk_relative_1_passport_or_permit text NOT NULL DEFAULT '',
    uk_relative_2_full_name text NOT NULL DEFAULT '',
    uk_relative_2_citizenship text NOT NULL DEFAULT '',
    uk_relative_2_stay_basis text NOT NULL DEFAULT '',
    uk_relative_2_passport_or_permit text NOT NULL DEFAULT '',

    had_uk_visa_before text NOT NULL DEFAULT '',
    uk_visa_issued_month_year text NOT NULL DEFAULT '',
    uk_visits_last_10_years text NOT NULL DEFAULT '',

    uk_trip_1_purpose text NOT NULL DEFAULT '',
    uk_trip_1_entry_date text NOT NULL DEFAULT '',
    uk_trip_1_exit_date text NOT NULL DEFAULT '',
    uk_trip_1_days_stayed text NOT NULL DEFAULT '',
    uk_trip_1_country text NOT NULL DEFAULT '',
    uk_trip_2_purpose text NOT NULL DEFAULT '',
    uk_trip_2_entry_date text NOT NULL DEFAULT '',
    uk_trip_2_exit_date text NOT NULL DEFAULT '',
    uk_trip_2_days_stayed text NOT NULL DEFAULT '',
    uk_trip_2_country text NOT NULL DEFAULT '',
    uk_trip_3_purpose text NOT NULL DEFAULT '',
    uk_trip_3_entry_date text NOT NULL DEFAULT '',
    uk_trip_3_exit_date text NOT NULL DEFAULT '',
    uk_trip_3_days_stayed text NOT NULL DEFAULT '',
    uk_trip_3_country text NOT NULL DEFAULT '',

    had_uk_visa_refusal text NOT NULL DEFAULT '',
    had_uk_entry_refusal text NOT NULL DEFAULT '',
    had_uk_deportation text NOT NULL DEFAULT '',
    uk_refusal_or_deportation_date text NOT NULL DEFAULT '',
    uk_refusal_or_deportation_reason text NOT NULL DEFAULT '',
    had_other_visa_refusal text NOT NULL DEFAULT '',
    had_other_entry_refusal text NOT NULL DEFAULT '',
    had_other_deportation text NOT NULL DEFAULT '',
    other_refusal_country text NOT NULL DEFAULT '',
    other_refusal_or_deportation_date text NOT NULL DEFAULT '',
    other_refusal_or_deportation_reason text NOT NULL DEFAULT '',
    traveled_abroad_last_10_years_excluding_uk text NOT NULL DEFAULT '',

    major_trip_1_purpose text NOT NULL DEFAULT '',
    major_trip_1_entry_date text NOT NULL DEFAULT '',
    major_trip_1_exit_date text NOT NULL DEFAULT '',
    major_trip_1_days_stayed text NOT NULL DEFAULT '',
    major_trip_1_country text NOT NULL DEFAULT '',
    major_trip_2_purpose text NOT NULL DEFAULT '',
    major_trip_2_entry_date text NOT NULL DEFAULT '',
    major_trip_2_exit_date text NOT NULL DEFAULT '',
    major_trip_2_days_stayed text NOT NULL DEFAULT '',
    major_trip_2_country text NOT NULL DEFAULT '',

    other_trip_1_purpose text NOT NULL DEFAULT '',
    other_trip_1_entry_date text NOT NULL DEFAULT '',
    other_trip_1_exit_date text NOT NULL DEFAULT '',
    other_trip_1_days_stayed text NOT NULL DEFAULT '',
    other_trip_1_country text NOT NULL DEFAULT '',
    other_trip_2_purpose text NOT NULL DEFAULT '',
    other_trip_2_entry_date text NOT NULL DEFAULT '',
    other_trip_2_exit_date text NOT NULL DEFAULT '',
    other_trip_2_days_stayed text NOT NULL DEFAULT '',
    other_trip_2_country text NOT NULL DEFAULT '',
    other_trip_3_purpose text NOT NULL DEFAULT '',
    other_trip_3_entry_date text NOT NULL DEFAULT '',
    other_trip_3_exit_date text NOT NULL DEFAULT '',
    other_trip_3_days_stayed text NOT NULL DEFAULT '',
    other_trip_3_country text NOT NULL DEFAULT '',

    convicted_criminal_offence text NOT NULL DEFAULT '',
    traffic_offence_penalty text NOT NULL DEFAULT '',
    charged_or_awaiting_trial text NOT NULL DEFAULT '',
    warning_or_other_penalty text NOT NULL DEFAULT '',
    civil_judgement_or_bankruptcy text NOT NULL DEFAULT '',
    criminal_details text NOT NULL DEFAULT '',
    involved_in_war_crimes_or_genocide text NOT NULL DEFAULT '',
    involved_with_terrorist_organization text NOT NULL DEFAULT '',
    expressed_terrorism_support_views text NOT NULL DEFAULT '',
    security_details text NOT NULL DEFAULT '',
    worked_in_listed_organizations text NOT NULL DEFAULT '',
    armed_forces_info text NOT NULL DEFAULT '',
    government_role_info text NOT NULL DEFAULT '',
    media_role_info text NOT NULL DEFAULT '',
    security_role_info text NOT NULL DEFAULT '',
    administrative_role_info text NOT NULL DEFAULT '',
    judicial_role_info text NOT NULL DEFAULT '',
    additional_information text NOT NULL DEFAULT '',
    biometric_submission_city text NOT NULL DEFAULT '',
    processed boolean NOT NULL DEFAULT false,

    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

 alter table  form.visa_application add COLUMN if not exists  processed boolean NOT NULL DEFAULT false;


CREATE INDEX IF NOT EXISTS idx_visa_application_created_at
    ON form.visa_application (created_at);

CREATE INDEX IF NOT EXISTS idx_visa_application_processed_created_at
    ON form.visa_application (processed, created_at);

COMMIT;